In [2]:
import numpy as np

dados = np.random.rand(2, 3) * 10
dados

array([[2.22734741, 7.40926912, 2.74660399],
       [1.77398166, 1.15704638, 6.68998088]])

In [3]:
dados.dtype

dtype('float64')

In [4]:
dados.shape

(2, 3)

In [5]:
dados.ndim

2

In [6]:
lista = [1, 2, 5.8, 9, 0.234, 99.23211]
dados2 = np.array(lista)
dados2

array([ 1.     ,  2.     ,  5.8    ,  9.     ,  0.234  , 99.23211])

In [7]:
dados_zero = np.zeros(11)
dados_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
dados_zero_2 = np.zeros((2, 3))
dados_zero_2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
dados_um = np.ones((5, 4))
dados_um

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
dados_seq = np.arange(10, 98)
dados_seq

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97])

## Just Multiply a value by itself

In [11]:
matrix = np.random.randint(50, size=(3, 3))
result = np.multiply(matrix, matrix)
print('the result is: ', result)
print('original matrix: ', matrix)

the result is:  [[1600  100  784]
 [1681 1225   81]
 [  49 1156 1024]]
original matrix:  [[40 10 28]
 [41 35  9]
 [ 7 34 32]]


## A real matrix product

In [12]:
result = np.matmul(matrix, matrix)
print(f'Result matrix: {result}')

Result matrix: [[2206 1702 2106]
 [3138 1941 1751]
 [1898 2348 1526]]


In [13]:
dados_copy = result[2:4].copy() # copia os valores, e não apenas o endereço de memória
dados_copy

array([[1898, 2348, 1526]])

## Mask

In [14]:
masked_value = (result>500) # will return return true or false for every value inside result
masked_value

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
another_result = result.copy()
another_result[another_result<500] = 222 # will give '222' for every value minor than 500
another_result, another_result.T

(array([[2206, 1702, 2106],
        [3138, 1941, 1751],
        [1898, 2348, 1526]]),
 array([[2206, 3138, 1898],
        [1702, 1941, 2348],
        [2106, 1751, 1526]]))

## Transposition od Matrix
With that command, we'll 'turn' the matrix axes

In [16]:
another_result, another_result.T # "T" is the method for transposition

(array([[2206, 1702, 2106],
        [3138, 1941, 1751],
        [1898, 2348, 1526]]),
 array([[2206, 3138, 1898],
        [1702, 1941, 2348],
        [2106, 1751, 1526]]))